services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "5000:5000"
  api:
    build: ./messaging-api
    container_name: messaging-api-container
    ports:
      - "3001:3001"
